server:
  port: 9530
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
    zookeeper:
      discovery:
        enabled: false
management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: ALWAYS
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,redis,info,health


